import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Adjust weights as needed
});

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${geist.variable} antialiased`}>
        <div>
          <NavigationBar />
          {children}
        </div>
      </body>
    </html>
  );
}
